# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  soTimeout: 501
  connectTimeout: 601
  trackerList:
    - 192.168.1.105:22122
#    - 192.168.174.47:22122
#    - 192.168.174.48:22122

spring.jmx.enabled: false